---
- import_tasks: set_vars.yml
  tags: [eclipse]

- import_tasks: download_to_master.yml
  when: eclipse_download_folder_remote is undefined 

- import_tasks: download_to_remote.yml
  when: eclipse_download_folder_remote is defined

- import_tasks: eclipse.yml
  tags: [eclipse]

- name: configure eclipse.ini
  import_tasks: eclipseini.yml
  tags: [eclipse]

- name: set vm from java-oracle role
  import_tasks: eclipseinijavavm.yml
  tags: [eclipse]

- import_tasks: plugins.yml
  tags: [eclipse]

- import_tasks: config.yml
